baseURL = "https://GenXXXX.github.io/"
languageCode = "en-us"
title = "ç™½é©¬ç°é©¬"
theme = "sam"

pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"
mathjax                 = true
enableEmoji             = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "No more knowledge can be extracted from my telling"

# Metadata
    description         = "No more knowledge can be extracted from my telling"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value â€œsummaryâ€, â€œsummary_large_imageâ€, â€œappâ€, or â€œplayerâ€
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/journal"
    text = "ğŸ“"

[[params.mainMenu]]
    link = "/hack"
    text = "ğŸ’¾"

[[params.mainMenu]]
    link = "/city"
    text = "ğŸŒ‰"

[[params.mainMenu]]
    link = "/sea"
    text = "ğŸŒŠ"

[[params.mainMenu]]
    link = "/mountain"
    text = "ğŸ—»"

[[params.mainMenu]]
    link = "/bnw"
    text = "ğŸ´â€â˜ ï¸"

[[params.mainMenu]]
    link = "/about"
    text = "ğŸ‘¹"

# Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = false # visitor count
    appId = 'LNWSFw5cWnONWCjuNFSms29s-gzGzoHsz'
    appKey = '71ucjbrEBKayqWojcceiAIWv'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'retro' 
    placeholder = 'Say something...'
    visitor = true
